---

source_containers:
    - single_cell_data:
        container_name: data
        storage_account: singlecelldata
        storage_key: aaskojf342l4j32lk4j2
    - single_cell_results:
        container_name: data
        storage_account: singlecelldata
        storage_key: aaskojf342l4j32lk4j2

destination_storage_account:
    - storage_account: singlecelldatabackup
    - storage_key: asljkdlkasjasjdfk

relative_log_path: logs/

...
